server:
  port: ${APP_START_PORT}
  servlet:
    context-path: ${APP_CONTEXT_PATH}
spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_DRIVER_URL}:${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
        ddl-auto: none
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates/
    suffix: .html
    encoding: UTF-8
  rabbitmq:
    username: ${BROKER_USER}
    password: ${BROKER_PASSWORD}
    host: ${BROKER_HOST}
    port: ${BROKER_PORT}
    listener:
      simple:
        retry:
          max-interval: 30000
          multiplier: 3.0
          max-attempts: 10
          enabled: true
          initial-interval: 5000