version: '3'

services:

  database:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./imports/db/:/docker-entrypoint-initdb.d/