version: '3.9'

services:

  psvm-rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - psvm-net

  psvm-postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./imports/db/:/docker-entrypoint-initdb.d/
    networks:
      - psvm-net

  psvm-liquibase:
    container_name: liquibase
    image: liquibase/liquibase
    command:
      - update
      - --url=jdbc:postgresql://psvm-postgres:5432/project?user=postgres&password=postgres
      - --changeLogFile=changelog.xml
    volumes:
      - ./liquibase/config/changelog.xml:/liquibase/changelog.xml
      - ./liquibase/scripts:/liquibase/scripts
    networks:
      - psvm-net
    depends_on:
      - psvm-postgres

  psvm-pms-app:
    container_name: pms-app
    image: pms-app
    ports:
      - "8080:8080"
    networks:
      - psvm-net
    depends_on:
      - psvm-postgres
      - psvm-rabbitmq

networks:
  psvm-net:
